{
 "nbformat": 4,
 "nbformat_minor": 0,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.0"}
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🚗 Driver Monitoring System — Notebook 2: Model Architecture & Inference\n",
    "\n",
    "Covers:\n",
    "- Real-time inference pipeline (webcam / video file)\n",
    "- EAR + MAR + Head Pose + Phone detection\n",
    "- YOLOv8 fine-tuning for phone detection\n",
    "- Evaluation metrics (confusion matrix, FPS benchmark)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 1 — Install & imports\n",
    "# ============================================================\n",
    "!pip install -q opencv-python mediapipe ultralytics scipy pygame imutils\n",
    "\n",
    "import sys, os\n",
    "sys.path.insert(0, '/content/driver_monitoring')  # adjust if needed\n",
    "\n",
    "import cv2\n",
    "import numpy as np\n",
    "import mediapipe as mp\n",
    "import time\n",
    "import matplotlib.pyplot as plt\n",
    "from IPython.display import display, Image\n",
    "from google.colab.patches import cv2_imshow\n",
    "\n",
    "from src.detectors import EARDetector, MARDetector, HeadPoseDetector, PhoneDetector, DetectionResult\n",
    "from src.alert_engine import AlertEngine, AudioAlert, OverlayRenderer, AlertConfig\n",
    "\n",
    "print('All imports OK')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 2 — Initialize all detectors\n",
    "# ============================================================\n",
    "mp_face_mesh = mp.solutions.face_mesh\n",
    "mp_drawing   = mp.solutions.drawing_utils\n",
    "\n",
    "face_mesh = mp_face_mesh.FaceMesh(\n",
    "    max_num_faces=1,\n",
    "    refine_landmarks=True,          # needed for iris, precise eye landmarks\n",
    "    min_detection_confidence=0.5,\n",
    "    min_tracking_confidence=0.5\n",
    ")\n",
    "\n",
    "# Detector configs — tune thresholds to your environment\n",
    "ear_detector  = EARDetector(ear_threshold=0.25, consec_frames=15)\n",
    "mar_detector  = MARDetector(mar_threshold=0.60, consec_frames=20)\n",
    "pose_detector = HeadPoseDetector(pitch_threshold=20.0, yaw_threshold=30.0, consec_frames=10)\n",
    "phone_det     = PhoneDetector(model_path='yolov8n.pt', confidence_threshold=0.45)\n",
    "\n",
    "cfg           = AlertConfig()\n",
    "alert_engine  = AlertEngine(cfg)\n",
    "renderer      = OverlayRenderer()\n",
    "\n",
    "print('Detectors initialized.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 3 — Core per-frame processing function\n",
    "# ============================================================\n",
    "\n",
    "def process_frame(frame: np.ndarray, use_phone_det: bool = True) -> DetectionResult:\n",
    "    \"\"\"\n",
    "    Run all detection modules on a single BGR frame.\n",
    "    Returns a populated DetectionResult.\n",
    "    \"\"\"\n",
    "    result = DetectionResult()\n",
    "    h, w = frame.shape[:2]\n",
    "    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "    # ── Face Mesh ──────────────────────────────────────────\n",
    "    mesh_result = face_mesh.process(rgb)\n",
    "\n",
    "    if mesh_result.multi_face_landmarks:\n",
    "        lm = mesh_result.multi_face_landmarks[0].landmark\n",
    "        ear_detector.process(lm, w, h, result)\n",
    "        mar_detector.process(lm, w, h, result)\n",
    "        pose_detector.process(lm, w, h, result)\n",
    "\n",
    "    # ── Phone detection (YOLO) ─────────────────────────────\n",
    "    if use_phone_det:\n",
    "        phone_det.process(frame, result)\n",
    "\n",
    "    # ── Alert fusion ───────────────────────────────────────\n",
    "    alert_engine.evaluate(result)\n",
    "\n",
    "    return result, mesh_result\n",
    "\n",
    "\n",
    "def draw_landmarks(frame, mesh_result, draw_mesh: bool = False):\n",
    "    \"\"\"Optionally draw face mesh on frame.\"\"\"\n",
    "    if mesh_result and mesh_result.multi_face_landmarks:\n",
    "        for face_lm in mesh_result.multi_face_landmarks:\n",
    "            if draw_mesh:\n",
    "                mp_drawing.draw_landmarks(\n",
    "                    frame, face_lm,\n",
    "                    mp.solutions.face_mesh.FACEMESH_CONTOURS,\n",
    "                    landmark_drawing_spec=mp_drawing.DrawingSpec(color=(0,255,0), thickness=1, circle_radius=1),\n",
    "                    connection_drawing_spec=mp_drawing.DrawingSpec(color=(0,150,0), thickness=1)\n",
    "                )\n",
    "\n",
    "print('process_frame() defined.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 4 — Run inference on a video file\n",
    "# ============================================================\n",
    "from google.colab import files\n",
    "\n",
    "print('Upload a test video (mp4/avi):')\n",
    "uploaded = files.upload()\n",
    "VIDEO_PATH = list(uploaded.keys())[0]\n",
    "print(f'Using: {VIDEO_PATH}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 5 — Process video and collect metrics\n",
    "# ============================================================\n",
    "import collections\n",
    "\n",
    "cap = cv2.VideoCapture(VIDEO_PATH)\n",
    "fps_src  = cap.get(cv2.CAP_PROP_FPS) or 30\n",
    "total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n",
    "\n",
    "OUT_PATH = VIDEO_PATH.replace('.mp4', '_annotated.mp4').replace('.avi', '_annotated.mp4')\n",
    "fourcc = cv2.VideoWriter_fourcc(*'mp4v')\n",
    "width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))\n",
    "height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))\n",
    "writer = cv2.VideoWriter(OUT_PATH, fourcc, fps_src, (width, height))\n",
    "\n",
    "# Metrics storage\n",
    "metrics_log = collections.defaultdict(list)\n",
    "prev_time   = time.time()\n",
    "frame_idx   = 0\n",
    "\n",
    "print(f'Processing {total_frames} frames at {fps_src:.0f} FPS...')\n",
    "\n",
    "while cap.isOpened():\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        break\n",
    "\n",
    "    result, mesh_result = process_frame(frame, use_phone_det=True)\n",
    "\n",
    "    # FPS calculation\n",
    "    now = time.time()\n",
    "    result.fps = 1.0 / (now - prev_time + 1e-9)\n",
    "    prev_time = now\n",
    "\n",
    "    # Log metrics\n",
    "    metrics_log['ear'].append(result.ear)\n",
    "    metrics_log['mar'].append(result.mar)\n",
    "    metrics_log['pitch'].append(result.pitch)\n",
    "    metrics_log['yaw'].append(result.yaw)\n",
    "    metrics_log['alert_level'].append(result.alert_level)\n",
    "    metrics_log['phone'].append(1 if result.phone_detected else 0)\n",
    "    metrics_log['fps'].append(result.fps)\n",
    "\n",
    "    # Draw\n",
    "    draw_landmarks(frame, mesh_result, draw_mesh=False)\n",
    "    pose_detector.draw_axes(frame, mesh_result.multi_face_landmarks[0].landmark if mesh_result.multi_face_landmarks else [], width, height)\n",
    "    phone_det.draw(frame, result)\n",
    "    renderer.render(frame, result)\n",
    "\n",
    "    writer.write(frame)\n",
    "    frame_idx += 1\n",
    "\n",
    "    if frame_idx % 100 == 0:\n",
    "        print(f'  Frame {frame_idx}/{total_frames} | FPS: {result.fps:.1f} | Alert: {result.alert_level}')\n",
    "\n",
    "cap.release()\n",
    "writer.release()\n",
    "print(f'Done. Output saved: {OUT_PATH}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 6 — Metrics dashboard\n",
    "# ============================================================\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "fig, axes = plt.subplots(3, 2, figsize=(14, 10))\n",
    "fig.suptitle('Driver Monitoring — Inference Metrics', fontsize=14, fontweight='bold')\n",
    "\n",
    "t = np.arange(len(metrics_log['ear'])) / fps_src  # time in seconds\n",
    "\n",
    "# EAR\n",
    "axes[0,0].plot(t, metrics_log['ear'], color='steelblue', linewidth=0.8)\n",
    "axes[0,0].axhline(0.25, color='red', linestyle='--', label='Threshold (0.25)')\n",
    "axes[0,0].set_title('Eye Aspect Ratio (EAR)')\n",
    "axes[0,0].set_ylabel('EAR'); axes[0,0].legend(); axes[0,0].grid(alpha=0.3)\n",
    "\n",
    "# MAR\n",
    "axes[0,1].plot(t, metrics_log['mar'], color='darkorange', linewidth=0.8)\n",
    "axes[0,1].axhline(0.60, color='red', linestyle='--', label='Threshold (0.60)')\n",
    "axes[0,1].set_title('Mouth Aspect Ratio (MAR)')\n",
    "axes[0,1].set_ylabel('MAR'); axes[0,1].legend(); axes[0,1].grid(alpha=0.3)\n",
    "\n",
    "# Head Pitch\n",
    "axes[1,0].plot(t, metrics_log['pitch'], color='purple', linewidth=0.8)\n",
    "axes[1,0].axhline(20, color='red', linestyle='--', label='+20° threshold')\n",
    "axes[1,0].axhline(-20, color='red', linestyle='--')\n",
    "axes[1,0].set_title('Head Pitch (°)')\n",
    "axes[1,0].set_ylabel('Degrees'); axes[1,0].legend(); axes[1,0].grid(alpha=0.3)\n",
    "\n",
    "# Head Yaw\n",
    "axes[1,1].plot(t, metrics_log['yaw'], color='teal', linewidth=0.8)\n",
    "axes[1,1].axhline(30, color='red', linestyle='--', label='+30° threshold')\n",
    "axes[1,1].axhline(-30, color='red', linestyle='--')\n",
    "axes[1,1].set_title('Head Yaw (°)')\n",
    "axes[1,1].set_ylabel('Degrees'); axes[1,1].legend(); axes[1,1].grid(alpha=0.3)\n",
    "\n",
    "# Alert levels over time\n",
    "colors_map = {0:'green', 1:'orange', 2:'red'}\n",
    "alert_arr = np.array(metrics_log['alert_level'])\n",
    "axes[2,0].scatter(t, alert_arr, c=[colors_map[a] for a in alert_arr],\n",
    "                  s=4, alpha=0.6)\n",
    "axes[2,0].set_yticks([0,1,2])\n",
    "axes[2,0].set_yticklabels(['Safe','Warning','Critical'])\n",
    "axes[2,0].set_title('Alert Level Timeline')\n",
    "axes[2,0].grid(alpha=0.3)\n",
    "\n",
    "# FPS\n",
    "axes[2,1].plot(t, metrics_log['fps'], color='navy', linewidth=0.7, alpha=0.7)\n",
    "axes[2,1].axhline(np.mean(metrics_log['fps']), color='red', linestyle='--',\n",
    "                   label=f'Avg: {np.mean(metrics_log[\"fps\"]):.1f} FPS')\n",
    "axes[2,1].set_title('Inference FPS')\n",
    "axes[2,1].set_ylabel('FPS'); axes[2,1].legend(); axes[2,1].grid(alpha=0.3)\n",
    "\n",
    "for ax in axes.flat:\n",
    "    ax.set_xlabel('Time (s)')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('/content/metrics_dashboard.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Dashboard saved.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 7 — Confusion Matrix (if ground-truth labels exist)\n",
    "# ============================================================\n",
    "from sklearn.metrics import confusion_matrix, classification_report\n",
    "import seaborn as sns\n",
    "\n",
    "# Simulate ground truth for demo; replace with actual labels\n",
    "# y_true format: 0=safe, 1=warning, 2=critical\n",
    "\n",
    "def evaluate_with_ground_truth(y_true, y_pred, class_names=['Safe','Warning','Critical']):\n",
    "    cm = confusion_matrix(y_true, y_pred)\n",
    "    report = classification_report(y_true, y_pred, target_names=class_names, digits=3)\n",
    "\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
    "\n",
    "    # Confusion matrix\n",
    "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',\n",
    "                xticklabels=class_names, yticklabels=class_names, ax=axes[0])\n",
    "    axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('True')\n",
    "    axes[0].set_title('Confusion Matrix')\n",
    "\n",
    "    # Normalized\n",
    "    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)\n",
    "    sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Greens',\n",
    "                xticklabels=class_names, yticklabels=class_names, ax=axes[1])\n",
    "    axes[1].set_xlabel('Predicted'); axes[1].set_ylabel('True')\n",
    "    axes[1].set_title('Normalized Confusion Matrix')\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.savefig('/content/confusion_matrix.png', dpi=150, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(report)\n",
    "\n",
    "# Uncomment and provide real labels:\n",
    "# evaluate_with_ground_truth(y_true_list, metrics_log['alert_level'])\n",
    "print('Evaluation function ready.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 8 — YOLOv8 Fine-tuning for phone detection\n",
    "# ============================================================\n",
    "# Dataset: https://universe.roboflow.com/roboflow-100/cell-phones-la4oe\n",
    "# Download as YOLOv8 format, place in /content/phone_dataset/\n",
    "\n",
    "from ultralytics import YOLO\n",
    "\n",
    "# 1. Load pretrained YOLOv8n (nano = fastest for Colab)\n",
    "model = YOLO('yolov8n.pt')\n",
    "\n",
    "# 2. Fine-tune on phone dataset\n",
    "results = model.train(\n",
    "    data='/content/phone_dataset/data.yaml',  # adjust path\n",
    "    epochs=50,\n",
    "    imgsz=640,\n",
    "    batch=16,\n",
    "    device=0,          # GPU; use 'cpu' if no GPU\n",
    "    project='/content/drive/MyDrive/DriverMonitoring/models',\n",
    "    name='phone_yolov8n',\n",
    "    patience=10,       # early stopping\n",
    "    save=True,\n",
    "    val=True,\n",
    "    plots=True,\n",
    "    # Data augmentation (built-in YOLOv8 augment)\n",
    "    hsv_h=0.015, hsv_s=0.7, hsv_v=0.4,\n",
    "    degrees=10.0,\n",
    "    flipud=0.0, fliplr=0.5,\n",
    "    mosaic=1.0,\n",
    "    mixup=0.0,\n",
    ")\n",
    "\n",
    "print('Training complete. Best model:', results.save_dir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 9 — ONNX Export for edge deployment\n",
    "# ============================================================\n",
    "from ultralytics import YOLO\n",
    "\n",
    "# Load best trained weights\n",
    "best_model = YOLO('/content/drive/MyDrive/DriverMonitoring/models/phone_yolov8n/weights/best.pt')\n",
    "\n",
    "# Export to ONNX (CPU-optimized)\n",
    "best_model.export(\n",
    "    format='onnx',\n",
    "    opset=17,\n",
    "    simplify=True,\n",
    "    imgsz=640\n",
    ")\n",
    "\n",
    "# Export to TFLite (for Raspberry Pi / Jetson)\n",
    "best_model.export(\n",
    "    format='tflite',\n",
    "    int8=False,\n",
    "    imgsz=640\n",
    ")\n",
    "\n",
    "print('Model exported to ONNX and TFLite.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 10 — FPS benchmark (CPU vs ONNX)\n",
    "# ============================================================\n",
    "import time\n",
    "import numpy as np\n",
    "\n",
    "def fps_benchmark(model, n_runs=100, img_size=640):\n",
    "    dummy = np.random.randint(0, 255, (img_size, img_size, 3), dtype=np.uint8)\n",
    "    \n",
    "    # Warmup\n",
    "    for _ in range(5):\n",
    "        model(dummy, verbose=False)\n",
    "    \n",
    "    times = []\n",
    "    for _ in range(n_runs):\n",
    "        t0 = time.perf_counter()\n",
    "        model(dummy, verbose=False)\n",
    "        times.append(time.perf_counter() - t0)\n",
    "    \n",
    "    times = np.array(times) * 1000  # ms\n",
    "    return {\n",
    "        'mean_ms': float(np.mean(times)),\n",
    "        'std_ms':  float(np.std(times)),\n",
    "        'fps':     float(1000 / np.mean(times)),\n",
    "        'p95_ms':  float(np.percentile(times, 95)),\n",
    "    }\n",
    "\n",
    "from ultralytics import YOLO\n",
    "\n",
    "print('Benchmarking YOLOv8n (PyTorch)...')\n",
    "pt_model = YOLO('yolov8n.pt')\n",
    "pt_bench = fps_benchmark(pt_model)\n",
    "print(f'  Mean: {pt_bench[\"mean_ms\"]:.1f}ms | FPS: {pt_bench[\"fps\"]:.1f} | P95: {pt_bench[\"p95_ms\"]:.1f}ms')\n",
    "\n",
    "# ONNX\n",
    "print('Benchmarking YOLOv8n (ONNX)...')\n",
    "onnx_model = YOLO('yolov8n.onnx')\n",
    "onnx_bench = fps_benchmark(onnx_model)\n",
    "print(f'  Mean: {onnx_bench[\"mean_ms\"]:.1f}ms | FPS: {onnx_bench[\"fps\"]:.1f} | P95: {onnx_bench[\"p95_ms\"]:.1f}ms')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# CELL 11 — Ablation study: EAR threshold sensitivity\n",
    "# ============================================================\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def run_ear_ablation(ear_values, ground_truth_closed, thresholds=None):\n",
    "    \"\"\"\n",
    "    Tests multiple EAR thresholds and returns precision/recall.\n",
    "    ear_values:        list of EAR values per frame\n",
    "    ground_truth_closed: list of booleans (True = eye closed)\n",
    "    \"\"\"\n",
    "    from sklearn.metrics import precision_score, recall_score, f1_score\n",
    "    if thresholds is None:\n",
    "        thresholds = np.arange(0.15, 0.40, 0.025)\n",
    "\n",
    "    results = []\n",
    "    for thr in thresholds:\n",
    "        y_pred = [1 if e < thr else 0 for e in ear_values]\n",
    "        y_true = [1 if g else 0 for g in ground_truth_closed]\n",
    "        results.append({\n",
    "            'threshold': thr,\n",
    "            'precision': precision_score(y_true, y_pred, zero_division=0),\n",
    "            'recall':    recall_score(y_true, y_pred, zero_division=0),\n",
    "            'f1':        f1_score(y_true, y_pred, zero_division=0),\n",
    "        })\n",
    "    return results\n",
    "\n",
    "# Example with logged EAR data:\n",
    "# ablation = run_ear_ablation(metrics_log['ear'], ground_truth)\n",
    "# thresholds = [r['threshold'] for r in ablation]\n",
    "# plt.plot(thresholds, [r['f1'] for r in ablation], label='F1')\n",
    "# plt.xlabel('EAR Threshold'); plt.ylabel('Score'); plt.title('EAR Ablation')\n",
    "# plt.legend(); plt.show()\n",
    "\n",
    "print('Ablation utility defined.')"
   ]
  }
 ]
}
