{
 "nbformat": 4,
 "nbformat_minor": 0,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.0"},
  "colab": {"provenance": [], "gpuType": "T4"},
  "accelerator": "GPU"
 },
 "cells": [

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🚗 Driver Drowsiness & Distraction Detection — End-to-End Run\n",
    "### Team 3 | Run this notebook top-to-bottom on Google Colab\n",
    "\n",
    "**Before starting:**\n",
    "1. Go to `Runtime → Change runtime type → T4 GPU`\n",
    "2. Upload `driver_monitoring.zip` when Cell 2 asks\n",
    "3. Upload `kaggle.json` when Cell 5 asks\n",
    "4. Run cells **one by one** in order\n",
    "\n",
    "**What this notebook does:**\n",
    "| Step | What happens |\n",
    "|------|--------------|\n",
    "| Cells 1–3 | Install packages, upload zip, extract project |\n",
    "| Cells 4–6 | Mount Drive, setup Kaggle, download datasets |\n",
    "| Cells 7–9 | Preprocess data, augmentation, train/val/test split |\n",
    "| Cells 10–12 | Initialize all 4 detectors |\n",
    "| Cells 13–14 | Test on sample images (quick sanity check) |\n",
    "| Cells 15–16 | Fine-tune YOLOv8 for phone detection |\n",
    "| Cells 17–18 | Run full inference on your video |\n",
    "| Cells 19–21 | Metrics dashboard, confusion matrix, ablation study |\n",
    "| Cells 22–23 | Export ONNX + TFLite, FPS benchmark |\n",
    "| Cell 24 | Download all results |\n"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 1 — Environment Setup"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 1 — Check GPU & install all packages\n",
    "# Expected time: ~2 minutes\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import subprocess\n",
    "\n",
    "# Verify GPU\n",
    "result = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total', '--format=csv,noheader'],\n",
    "                        capture_output=True, text=True)\n",
    "if result.returncode == 0:\n",
    "    print(f'GPU detected: {result.stdout.strip()}')\n",
    "else:\n",
    "    print('WARNING: No GPU detected. Go to Runtime → Change runtime type → T4 GPU')\n",
    "\n",
    "# Install all required packages\n",
    "!pip install -q \\\n",
    "    opencv-python \\\n",
    "    mediapipe==0.10.11 \\\n",
    "    ultralytics \\\n",
    "    scipy \\\n",
    "    matplotlib \\\n",
    "    seaborn \\\n",
    "    pandas \\\n",
    "    scikit-learn \\\n",
    "    Pillow \\\n",
    "    pygame \\\n",
    "    tqdm \\\n",
    "    imutils \\\n",
    "    gdown \\\n",
    "    kaggle\n",
    "\n",
    "print('\\nAll packages installed successfully!')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 2 — Upload and extract the project zip\n",
    "# ACTION: Upload driver_monitoring.zip when the button appears\n",
    "# ══════════════════════════════════════════════════════════\n",
    "from google.colab import files\n",
    "import zipfile, os\n",
    "\n",
    "print('Please upload driver_monitoring.zip')\n",
    "uploaded = files.upload()\n",
    "\n",
    "zip_name = [k for k in uploaded.keys() if k.endswith('.zip')][0]\n",
    "print(f'Extracting {zip_name}...')\n",
    "\n",
    "with zipfile.ZipFile(zip_name, 'r') as z:\n",
    "    z.extractall('/content/')\n",
    "\n",
    "print('Extracted to /content/driver_monitoring/')\n",
    "os.listdir('/content/driver_monitoring/')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 3 — Add project to Python path\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import sys\n",
    "PROJECT_ROOT = '/content/driver_monitoring'\n",
    "if PROJECT_ROOT not in sys.path:\n",
    "    sys.path.insert(0, PROJECT_ROOT)\n",
    "\n",
    "# Verify imports work\n",
    "from src.detectors import EARDetector, MARDetector, HeadPoseDetector, PhoneDetector, DetectionResult\n",
    "from src.alert_engine import AlertEngine, OverlayRenderer, AlertConfig\n",
    "\n",
    "print('Project imported successfully!')\n",
    "print('src/detectors.py   OK')\n",
    "print('src/alert_engine.py OK')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 2 — Google Drive & Dataset Download"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 4 — Mount Google Drive (saves datasets permanently)\n",
    "# This means you won't re-download each session\n",
    "# ══════════════════════════════════════════════════════════\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "\n",
    "import os\n",
    "BASE   = '/content/drive/MyDrive/DriverMonitoring'\n",
    "RAW    = f'{BASE}/data/raw'\n",
    "PROC   = f'{BASE}/data/processed'\n",
    "MODELS = f'{BASE}/models'\n",
    "RESULTS= f'{BASE}/results'\n",
    "\n",
    "for d in [RAW, PROC, MODELS, RESULTS]:\n",
    "    os.makedirs(d, exist_ok=True)\n",
    "\n",
    "print('Drive mounted. Folders created:')\n",
    "for d in [RAW, PROC, MODELS, RESULTS]:\n",
    "    print(f'  {d}')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 5 — Setup Kaggle API\n",
    "# ACTION: Upload your kaggle.json file when prompted\n",
    "# Get it from: kaggle.com → Account → API → Create New Token\n",
    "# ══════════════════════════════════════════════════════════\n",
    "from google.colab import files\n",
    "import os, shutil\n",
    "\n",
    "# Check if already configured (from a previous session)\n",
    "if os.path.exists('/root/.kaggle/kaggle.json'):\n",
    "    print('Kaggle API already configured. Skipping upload.')\n",
    "else:\n",
    "    print('Upload your kaggle.json:')\n",
    "    uploaded = files.upload()\n",
    "    os.makedirs('/root/.kaggle', exist_ok=True)\n",
    "    shutil.move('kaggle.json', '/root/.kaggle/kaggle.json')\n",
    "    os.chmod('/root/.kaggle/kaggle.json', 0o600)\n",
    "    print('Kaggle API configured!')\n",
    "\n",
    "# Test it\n",
    "!kaggle datasets list --max-size 1 2>&1 | head -3"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 6 — Download all datasets\n",
    "# Expected time: 5–15 minutes (depends on internet speed)\n",
    "# Skips datasets already downloaded to Drive\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import os\n",
    "\n",
    "datasets = {\n",
    "    'mrl_eye':    ('imadeddinedjerarda/mrl-eye-dataset',          'MRL Eye (84k images)'),\n",
    "    'yawn':       ('davidvazquezcic/yawn-eye-dataset-new',        'Yawn Detection (3k images)'),\n",
    "    'drowsy_drv': ('ismailnasri20/driver-drowsiness-dataset',     'Driver Drowsiness Dataset'),\n",
    "}\n",
    "\n",
    "for folder, (slug, name) in datasets.items():\n",
    "    dest = f'{RAW}/{folder}'\n",
    "    # Skip if already downloaded\n",
    "    if os.path.exists(dest) and len(os.listdir(dest)) > 0:\n",
    "        print(f'[SKIP] {name} — already in Drive')\n",
    "        continue\n",
    "    os.makedirs(dest, exist_ok=True)\n",
    "    print(f'Downloading {name}...')\n",
    "    ret = os.system(f'kaggle datasets download -d {slug} -p {dest} --unzip -q')\n",
    "    if ret == 0:\n",
    "        n = sum(len(f) for _, _, f in os.walk(dest))\n",
    "        print(f'  Done: {n} files')\n",
    "    else:\n",
    "        print(f'  ERROR downloading {name}. Check your Kaggle API key.')\n",
    "\n",
    "# Phone dataset (Roboflow — manual download instructions)\n",
    "print('\\nFor phone detection dataset:')\n",
    "print('  1. Go to: https://universe.roboflow.com/roboflow-100/cell-phones-la4oe')\n",
    "print('  2. Download as YOLOv8 format')\n",
    "print(f'  3. Upload the zip and extract to {RAW}/phone_yolo/')\n",
    "print('  (OR skip — the pretrained COCO weights already detect phones reasonably well)')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 3 — Preprocessing & EDA"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 7 — Exploratory Data Analysis (EDA)\n",
    "# Produces plots you can paste directly into your report\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import os, matplotlib.pyplot as plt\n",
    "import matplotlib.image as mpimg\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "\n",
    "def eda_dataset(root_path, name, max_samples_per_class=3):\n",
    "    root = Path(root_path)\n",
    "    if not root.exists():\n",
    "        print(f'[SKIP] {name} not found at {root_path}')\n",
    "        return\n",
    "\n",
    "    classes = sorted([d for d in root.iterdir() if d.is_dir()])\n",
    "    if not classes:\n",
    "        # Flat directory — treat as single class\n",
    "        imgs = list(root.glob('*.jpg')) + list(root.glob('*.png'))\n",
    "        print(f'{name}: {len(imgs)} images (flat directory)')\n",
    "        return\n",
    "\n",
    "    counts = {c.name: len(list(c.glob('*.jpg'))+list(c.glob('*.png'))) for c in classes}\n",
    "\n",
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n",
    "    fig.suptitle(f'EDA: {name}', fontsize=13, fontweight='bold')\n",
    "\n",
    "    # Bar chart\n",
    "    bars = axes[0].bar(counts.keys(), counts.values(),\n",
    "                        color=['#4C72B0','#DD8452','#55A868','#C44E52'][:len(counts)])\n",
    "    axes[0].set_title('Class distribution')\n",
    "    axes[0].set_ylabel('Image count')\n",
    "    for bar, val in zip(bars, counts.values()):\n",
    "        axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+50,\n",
    "                     str(val), ha='center', fontsize=10)\n",
    "    axes[0].tick_params(axis='x', rotation=15)\n",
    "\n",
    "    # Pie chart\n",
    "    axes[1].pie(counts.values(), labels=counts.keys(), autopct='%1.1f%%',\n",
    "                colors=['#4C72B0','#DD8452','#55A868','#C44E52'][:len(counts)])\n",
    "    axes[1].set_title('Class balance')\n",
    "\n",
    "    plt.tight_layout()\n",
    "    save_path = f'{RESULTS}/{name.replace(\" \",\"_\")}_eda.png'\n",
    "    plt.savefig(save_path, dpi=150, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(f'Saved: {save_path}')\n",
    "    print(f'Total images: {sum(counts.values())} across {len(classes)} classes')\n",
    "\n",
    "eda_dataset(f'{RAW}/yawn',       'Yawn Dataset')\n",
    "eda_dataset(f'{RAW}/drowsy_drv', 'Driver Drowsiness Dataset')\n",
    "eda_dataset(f'{RAW}/mrl_eye',    'MRL Eye Dataset')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 8 — Show sample images from each class\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import cv2, random\n",
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def show_samples(root_path, name, n_per_class=4):\n",
    "    root = Path(root_path)\n",
    "    if not root.exists():\n",
    "        print(f'[SKIP] {name}')\n",
    "        return\n",
    "    classes = sorted([d for d in root.iterdir() if d.is_dir()])\n",
    "    if not classes:\n",
    "        return\n",
    "\n",
    "    fig, axes = plt.subplots(len(classes), n_per_class,\n",
    "                              figsize=(n_per_class*2.5, len(classes)*2.5))\n",
    "    fig.suptitle(f'Sample images: {name}', fontsize=13, fontweight='bold')\n",
    "    if len(classes) == 1:\n",
    "        axes = [axes]\n",
    "\n",
    "    for i, cls_dir in enumerate(classes):\n",
    "        imgs = list(cls_dir.glob('*.jpg')) + list(cls_dir.glob('*.png'))\n",
    "        random.shuffle(imgs)\n",
    "        for j in range(n_per_class):\n",
    "            ax = axes[i][j] if n_per_class > 1 else axes[i]\n",
    "            if j < len(imgs):\n",
    "                img = cv2.imread(str(imgs[j]))\n",
    "                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "                ax.imshow(img)\n",
    "            ax.axis('off')\n",
    "            if j == 0:\n",
    "                ax.set_ylabel(cls_dir.name, fontsize=10, rotation=0,\n",
    "                              labelpad=50, va='center')\n",
    "\n",
    "    plt.tight_layout()\n",
    "    save_path = f'{RESULTS}/{name.replace(\" \",\"_\")}_samples.png'\n",
    "    plt.savefig(save_path, dpi=120, bbox_inches='tight')\n",
    "    plt.show()\n",
    "\n",
    "show_samples(f'{RAW}/yawn', 'Yawn Dataset')\n",
    "show_samples(f'{RAW}/drowsy_drv', 'Driver Drowsiness Dataset')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 9 — Preprocess + split dataset\n",
    "# 70% train / 15% val / 15% test — stratified per class\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import shutil, random\n",
    "from pathlib import Path\n",
    "from tqdm import tqdm\n",
    "\n",
    "def split_dataset(src_root, dst_root, splits=(0.70, 0.15, 0.15), seed=42):\n",
    "    random.seed(seed)\n",
    "    src = Path(src_root)\n",
    "    dst = Path(dst_root)\n",
    "    if not src.exists():\n",
    "        print(f'[SKIP] {src_root} not found')\n",
    "        return\n",
    "\n",
    "    for split in ['train', 'val', 'test']:\n",
    "        (dst / split).mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "    total_moved = 0\n",
    "    for cls_dir in sorted(src.iterdir()):\n",
    "        if not cls_dir.is_dir():\n",
    "            continue\n",
    "        images = list(cls_dir.glob('*.jpg')) + list(cls_dir.glob('*.png'))\n",
    "        random.shuffle(images)\n",
    "        n = len(images)\n",
    "        n_train = int(n * splits[0])\n",
    "        n_val   = int(n * splits[1])\n",
    "        parts = {\n",
    "            'train': images[:n_train],\n",
    "            'val':   images[n_train:n_train+n_val],\n",
    "            'test':  images[n_train+n_val:]\n",
    "        }\n",
    "        for split, imgs in parts.items():\n",
    "            out = dst / split / cls_dir.name\n",
    "            out.mkdir(exist_ok=True)\n",
    "            for img in imgs:\n",
    "                shutil.copy2(img, out / img.name)\n",
    "        total_moved += n\n",
    "        print(f'  {cls_dir.name:25s}: train={len(parts[\"train\"]):5d}  val={len(parts[\"val\"]):4d}  test={len(parts[\"test\"]):4d}')\n",
    "\n",
    "    print(f'Total: {total_moved} images split into {dst}')\n",
    "\n",
    "print('Splitting yawn dataset...')\n",
    "split_dataset(f'{RAW}/yawn',       f'{PROC}/yawn_split')\n",
    "\n",
    "print('\\nSplitting drowsiness dataset...')\n",
    "split_dataset(f'{RAW}/drowsy_drv', f'{PROC}/drowsy_split')\n",
    "\n",
    "print('\\nDone!')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 4 — Initialize All Detectors"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 10 — Initialize MediaPipe + all 4 detectors\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import cv2\n",
    "import numpy as np\n",
    "import mediapipe as mp\n",
    "import time\n",
    "import matplotlib.pyplot as plt\n",
    "from google.colab.patches import cv2_imshow\n",
    "\n",
    "from src.detectors import EARDetector, MARDetector, HeadPoseDetector, PhoneDetector, DetectionResult\n",
    "from src.alert_engine import AlertEngine, OverlayRenderer, AlertConfig\n",
    "\n",
    "# MediaPipe FaceMesh\n",
    "mp_face_mesh = mp.solutions.face_mesh\n",
    "mp_drawing   = mp.solutions.drawing_utils\n",
    "\n",
    "face_mesh = mp_face_mesh.FaceMesh(\n",
    "    max_num_faces=1,\n",
    "    refine_landmarks=True,\n",
    "    min_detection_confidence=0.5,\n",
    "    min_tracking_confidence=0.5\n",
    ")\n",
    "\n",
    "# Detectors\n",
    "ear_detector  = EARDetector(ear_threshold=0.25,  consec_frames=15)\n",
    "mar_detector  = MARDetector(mar_threshold=0.60,  consec_frames=20)\n",
    "pose_detector = HeadPoseDetector(pitch_threshold=20.0, yaw_threshold=30.0, consec_frames=10)\n",
    "phone_det     = PhoneDetector(model_path='yolov8n.pt', confidence_threshold=0.45)\n",
    "\n",
    "# Alert engine\n",
    "alert_engine  = AlertEngine(AlertConfig())\n",
    "renderer      = OverlayRenderer()\n",
    "\n",
    "print('All detectors initialized:')\n",
    "print('  EARDetector     — threshold=0.25, frames=15')\n",
    "print('  MARDetector     — threshold=0.60, frames=20')\n",
    "print('  HeadPoseDetector— pitch=20°, yaw=30°, frames=10')\n",
    "print('  PhoneDetector   — YOLOv8n, conf=0.45')\n",
    "print('  AlertEngine     — fusion weights: EAR=35%, Head=25%, MAR=20%, Phone=20%')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 11 — Core process_frame() function\n",
    "# ══════════════════════════════════════════════════════════\n",
    "\n",
    "def process_frame(frame, use_phone_det=True):\n",
    "    result = DetectionResult()\n",
    "    h, w = frame.shape[:2]\n",
    "    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "    # Face mesh\n",
    "    mesh_result = face_mesh.process(rgb)\n",
    "\n",
    "    if mesh_result.multi_face_landmarks:\n",
    "        lm = mesh_result.multi_face_landmarks[0].landmark\n",
    "        ear_detector.process(lm, w, h, result)\n",
    "        mar_detector.process(lm, w, h, result)\n",
    "        pose_detector.process(lm, w, h, result)\n",
    "\n",
    "    if use_phone_det:\n",
    "        phone_det.process(frame, result)\n",
    "\n",
    "    alert_engine.evaluate(result)\n",
    "    return result, mesh_result\n",
    "\n",
    "print('process_frame() ready.')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 5 — Quick Sanity Check on Sample Images"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 12 — Test on sample images from your dataset\n",
    "# Verifies EAR, MAR, head pose are working correctly\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import cv2\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from pathlib import Path\n",
    "import random\n",
    "\n",
    "def test_on_sample_images(dataset_root, n_samples=6):\n",
    "    root = Path(dataset_root)\n",
    "    if not root.exists():\n",
    "        print(f'Dataset not found: {dataset_root}')\n",
    "        return\n",
    "\n",
    "    all_imgs = list(root.rglob('*.jpg')) + list(root.rglob('*.png'))\n",
    "    if not all_imgs:\n",
    "        print('No images found.')\n",
    "        return\n",
    "\n",
    "    samples = random.sample(all_imgs, min(n_samples, len(all_imgs)))\n",
    "\n",
    "    fig, axes = plt.subplots(2, 3, figsize=(14, 8))\n",
    "    fig.suptitle('Detector Test on Sample Images', fontsize=13, fontweight='bold')\n",
    "\n",
    "    for ax, img_path in zip(axes.flat, samples):\n",
    "        frame = cv2.imread(str(img_path))\n",
    "        if frame is None:\n",
    "            continue\n",
    "        frame = cv2.resize(frame, (640, 480))\n",
    "\n",
    "        result, mesh_result = process_frame(frame, use_phone_det=False)\n",
    "        renderer.render(frame, result)\n",
    "\n",
    "        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "        ax.imshow(frame_rgb)\n",
    "        ax.set_title(\n",
    "            f'EAR={result.ear:.2f} MAR={result.mar:.2f}\\n'\n",
    "            f'Pitch={result.pitch:.0f}° Yaw={result.yaw:.0f}°\\n'\n",
    "            f'Alert: {[\"Safe\",\"Warning\",\"Critical\"][result.alert_level]}',\n",
    "            fontsize=9\n",
    "        )\n",
    "        ax.axis('off')\n",
    "\n",
    "    plt.tight_layout()\n",
    "    save_path = f'{RESULTS}/sanity_check.png'\n",
    "    plt.savefig(save_path, dpi=130, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(f'Saved: {save_path}')\n",
    "\n",
    "# Try on whatever dataset downloaded first\n",
    "for path in [f'{RAW}/yawn', f'{RAW}/drowsy_drv', f'{RAW}/mrl_eye']:\n",
    "    if Path(path).exists():\n",
    "        test_on_sample_images(path)\n",
    "        break"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 6 — YOLOv8 Fine-tuning for Phone Detection"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 13 — Option A: Use pretrained COCO (no custom training)\n",
    "# This works well for a demo. Skip to CELL 14 if you want\n",
    "# to fine-tune on a phone-specific dataset.\n",
    "# ══════════════════════════════════════════════════════════\n",
    "from ultralytics import YOLO\n",
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "# Load pretrained YOLOv8n (COCO) — phone = class 67\n",
    "yolo_model = YOLO('yolov8n.pt')\n",
    "\n",
    "# Quick test: create a dummy image and run inference\n",
    "dummy = np.random.randint(100, 200, (480, 640, 3), dtype=np.uint8)\n",
    "preds = yolo_model(dummy, classes=[67], conf=0.45, verbose=False)\n",
    "print('YOLOv8n pretrained model loaded and working.')\n",
    "print(f'Model size: {sum(p.numel() for p in yolo_model.model.parameters()):,} parameters')\n",
    "print('\\nFor demo purposes, this pretrained model detects phones from COCO.')\n",
    "print('To fine-tune, run CELL 14.')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 14 — Option B: Fine-tune YOLOv8 on phone dataset\n",
    "# SKIP THIS CELL if you don't have the Roboflow dataset\n",
    "# Expected time: ~25-35 minutes on T4 GPU\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import os\n",
    "from ultralytics import YOLO\n",
    "\n",
    "PHONE_DATASET = f'{RAW}/phone_yolo'  # path to Roboflow YOLOv8 dataset\n",
    "DATA_YAML     = f'{PHONE_DATASET}/data.yaml'\n",
    "\n",
    "if not os.path.exists(DATA_YAML):\n",
    "    print('Phone dataset not found. Instructions:')\n",
    "    print('  1. Visit https://universe.roboflow.com/roboflow-100/cell-phones-la4oe')\n",
    "    print('  2. Download as \"YOLOv8\" format')\n",
    "    print(f'  3. Upload zip and extract to {PHONE_DATASET}/')\n",
    "    print('  Then re-run this cell.')\n",
    "else:\n",
    "    model = YOLO('yolov8n.pt')\n",
    "    results = model.train(\n",
    "        data=DATA_YAML,\n",
    "        epochs=50,\n",
    "        imgsz=640,\n",
    "        batch=16,\n",
    "        device=0,\n",
    "        project=MODELS,\n",
    "        name='phone_yolov8n',\n",
    "        patience=10,\n",
    "        save=True,\n",
    "        val=True,\n",
    "        plots=True,\n",
    "        hsv_h=0.015, hsv_s=0.7, hsv_v=0.4,\n",
    "        degrees=10.0, fliplr=0.5, mosaic=1.0,\n",
    "        verbose=True\n",
    "    )\n",
    "    BEST_WEIGHTS = f'{MODELS}/phone_yolov8n/weights/best.pt'\n",
    "    print(f'Training done. Best weights: {BEST_WEIGHTS}')\n",
    "\n",
    "    # Update phone detector to use fine-tuned weights\n",
    "    phone_det._model_path = BEST_WEIGHTS\n",
    "    phone_det.model = None  # force reload\n",
    "    print('PhoneDetector updated to use fine-tuned weights.')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 7 — Run Full Inference on Your Video"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 15 — Upload your test video\n",
    "# Record a 1-2 min video of yourself driving (or sitting)\n",
    "# Include: yawning, closing eyes, looking away, holding phone\n",
    "# ══════════════════════════════════════════════════════════\n",
    "from google.colab import files\n",
    "import os\n",
    "\n",
    "print('Upload your test video (mp4/avi, 1-2 minutes):')\n",
    "print('TIP: Record yourself with webcam. Include these actions:')\n",
    "print('  - Eyes closed for 2+ seconds (drowsiness)')\n",
    "print('  - Wide yawning (mouth open)')\n",
    "print('  - Looking left/right away from camera (distraction)')\n",
    "print('  - Holding a phone near your face')\n",
    "print()\n",
    "\n",
    "uploaded = files.upload()\n",
    "VIDEO_PATH = list(uploaded.keys())[0]\n",
    "\n",
    "# Copy to Drive for persistence\n",
    "import shutil\n",
    "drive_video = f'{BASE}/test_video_{VIDEO_PATH}'\n",
    "shutil.copy(VIDEO_PATH, drive_video)\n",
    "\n",
    "print(f'\\nVideo ready: {VIDEO_PATH}')\n",
    "\n",
    "# Quick info\n",
    "import cv2\n",
    "cap = cv2.VideoCapture(VIDEO_PATH)\n",
    "fps = cap.get(cv2.CAP_PROP_FPS)\n",
    "frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n",
    "w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))\n",
    "h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))\n",
    "cap.release()\n",
    "print(f'  Resolution: {w}x{h}')\n",
    "print(f'  FPS: {fps:.0f}')\n",
    "print(f'  Duration: {frames/fps:.1f} seconds ({frames} frames)')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 16 — Run full inference pipeline on video\n",
    "# Saves annotated output video + logs all metrics\n",
    "# Expected time: ~1 min per minute of video\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import cv2\n",
    "import numpy as np\n",
    "import time\n",
    "import collections\n",
    "from tqdm import tqdm\n",
    "\n",
    "# Reset all detector states\n",
    "ear_detector.reset()\n",
    "mar_detector.reset()\n",
    "pose_detector.reset()\n",
    "\n",
    "cap = cv2.VideoCapture(VIDEO_PATH)\n",
    "fps_src     = cap.get(cv2.CAP_PROP_FPS) or 30\n",
    "total_frames= int(cap.get(cv2.CAP_PROP_FRAME_COUNT))\n",
    "width       = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))\n",
    "height      = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))\n",
    "\n",
    "OUT_VIDEO = f'{RESULTS}/output_annotated.mp4'\n",
    "fourcc = cv2.VideoWriter_fourcc(*'mp4v')\n",
    "writer = cv2.VideoWriter(OUT_VIDEO, fourcc, fps_src, (width, height))\n",
    "\n",
    "# Metrics log\n",
    "metrics_log = collections.defaultdict(list)\n",
    "prev_t = time.time()\n",
    "\n",
    "print(f'Processing {total_frames} frames at {fps_src:.0f} FPS...')\n",
    "\n",
    "for frame_idx in tqdm(range(total_frames)):\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        break\n",
    "\n",
    "    result, mesh_result = process_frame(frame, use_phone_det=True)\n",
    "\n",
    "    now = time.time()\n",
    "    result.fps = 1.0 / max(now - prev_t, 1e-9)\n",
    "    prev_t = now\n",
    "\n",
    "    # Log metrics every frame\n",
    "    metrics_log['ear'].append(result.ear)\n",
    "    metrics_log['mar'].append(result.mar)\n",
    "    metrics_log['pitch'].append(result.pitch)\n",
    "    metrics_log['yaw'].append(result.yaw)\n",
    "    metrics_log['alert_level'].append(result.alert_level)\n",
    "    metrics_log['phone'].append(int(result.phone_detected))\n",
    "    metrics_log['fps'].append(result.fps)\n",
    "\n",
    "    # Draw phone bbox if detected\n",
    "    phone_det.draw(frame, result)\n",
    "\n",
    "    # Draw HUD overlay\n",
    "    renderer.render(frame, result)\n",
    "\n",
    "    writer.write(frame)\n",
    "\n",
    "cap.release()\n",
    "writer.release()\n",
    "\n",
    "import numpy as np\n",
    "alert_arr = np.array(metrics_log['alert_level'])\n",
    "print(f'\\nInference complete!')\n",
    "print(f'  Output video: {OUT_VIDEO}')\n",
    "print(f'  Avg FPS: {np.mean(metrics_log[\"fps\"]):.1f}')\n",
    "print(f'  Alerts — Safe: {(alert_arr==0).sum()} | Warning: {(alert_arr==1).sum()} | Critical: {(alert_arr==2).sum()}')\n",
    "print(f'  Phone detected in {np.sum(metrics_log[\"phone\"])} frames')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 8 — Evaluation & Metrics"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 17 — Full metrics dashboard\n",
    "# Save this plot for your report!\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "fig, axes = plt.subplots(3, 2, figsize=(15, 11))\n",
    "fig.suptitle('Driver Monitoring System — Inference Metrics Dashboard', fontsize=14, fontweight='bold')\n",
    "\n",
    "t = np.arange(len(metrics_log['ear'])) / fps_src\n",
    "\n",
    "# 1. EAR over time\n",
    "axes[0,0].plot(t, metrics_log['ear'], color='#2196F3', linewidth=0.8, label='EAR')\n",
    "axes[0,0].fill_between(t, metrics_log['ear'], 0.25, where=np.array(metrics_log['ear'])<0.25,\n",
    "                        color='red', alpha=0.3, label='Drowsy zone')\n",
    "axes[0,0].axhline(0.25, color='red', linestyle='--', linewidth=1.2, label='Threshold')\n",
    "axes[0,0].set_title('Eye Aspect Ratio (EAR)', fontweight='bold')\n",
    "axes[0,0].set_ylabel('EAR'); axes[0,0].legend(fontsize=8); axes[0,0].grid(alpha=0.3)\n",
    "axes[0,0].set_ylim(0, 0.5)\n",
    "\n",
    "# 2. MAR over time\n",
    "axes[0,1].plot(t, metrics_log['mar'], color='#FF9800', linewidth=0.8, label='MAR')\n",
    "axes[0,1].fill_between(t, metrics_log['mar'], 0.60, where=np.array(metrics_log['mar'])>0.60,\n",
    "                        color='orange', alpha=0.3, label='Yawn zone')\n",
    "axes[0,1].axhline(0.60, color='darkorange', linestyle='--', linewidth=1.2, label='Threshold')\n",
    "axes[0,1].set_title('Mouth Aspect Ratio (MAR)', fontweight='bold')\n",
    "axes[0,1].set_ylabel('MAR'); axes[0,1].legend(fontsize=8); axes[0,1].grid(alpha=0.3)\n",
    "\n",
    "# 3. Head pitch\n",
    "axes[1,0].plot(t, metrics_log['pitch'], color='#9C27B0', linewidth=0.8)\n",
    "axes[1,0].axhspan(20, max(max(metrics_log['pitch']), 25), color='red', alpha=0.1, label='Distracted zone')\n",
    "axes[1,0].axhspan(min(min(metrics_log['pitch']), -25), -20, color='red', alpha=0.1)\n",
    "axes[1,0].axhline(20, color='red', linestyle='--', linewidth=1); axes[1,0].axhline(-20, color='red', linestyle='--', linewidth=1)\n",
    "axes[1,0].set_title('Head Pitch (°)', fontweight='bold')\n",
    "axes[1,0].set_ylabel('Degrees'); axes[1,0].legend(fontsize=8); axes[1,0].grid(alpha=0.3)\n",
    "\n",
    "# 4. Head yaw\n",
    "axes[1,1].plot(t, metrics_log['yaw'], color='#009688', linewidth=0.8)\n",
    "axes[1,1].axhspan(30, max(max(metrics_log['yaw']), 35), color='red', alpha=0.1)\n",
    "axes[1,1].axhspan(min(min(metrics_log['yaw']), -35), -30, color='red', alpha=0.1)\n",
    "axes[1,1].axhline(30, color='red', linestyle='--', linewidth=1); axes[1,1].axhline(-30, color='red', linestyle='--', linewidth=1)\n",
    "axes[1,1].set_title('Head Yaw (°)', fontweight='bold')\n",
    "axes[1,1].set_ylabel('Degrees'); axes[1,1].grid(alpha=0.3)\n",
    "\n",
    "# 5. Alert level timeline\n",
    "alert_arr = np.array(metrics_log['alert_level'])\n",
    "colors_map = {0:'#4CAF50', 1:'#FF9800', 2:'#F44336'}\n",
    "for lvl, color in colors_map.items():\n",
    "    mask = alert_arr == lvl\n",
    "    axes[2,0].fill_between(t, 0, 1, where=mask, color=color, alpha=0.6,\n",
    "                            label=['Safe','Warning','Critical'][lvl])\n",
    "axes[2,0].set_title('Alert Level Timeline', fontweight='bold')\n",
    "axes[2,0].set_yticks([]); axes[2,0].legend(fontsize=8); axes[2,0].grid(alpha=0.2)\n",
    "\n",
    "# 6. FPS\n",
    "fps_arr = np.array(metrics_log['fps'])\n",
    "axes[2,1].plot(t, fps_arr, color='#607D8B', linewidth=0.6, alpha=0.7)\n",
    "axes[2,1].axhline(np.mean(fps_arr), color='navy', linestyle='--',\n",
    "                   label=f'Avg: {np.mean(fps_arr):.1f} FPS')\n",
    "axes[2,1].set_title('Inference FPS', fontweight='bold')\n",
    "axes[2,1].set_ylabel('FPS'); axes[2,1].legend(fontsize=8); axes[2,1].grid(alpha=0.3)\n",
    "\n",
    "for ax in axes.flat:\n",
    "    ax.set_xlabel('Time (s)')\n",
    "\n",
    "plt.tight_layout()\n",
    "DASH_PATH = f'{RESULTS}/metrics_dashboard.png'\n",
    "plt.savefig(DASH_PATH, dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Dashboard saved: {DASH_PATH}')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 18 — EAR Ablation Study (required for 14-mark section)\n",
    "# Tests multiple threshold values to find the optimal one\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "ear_values = metrics_log['ear']\n",
    "\n",
    "# Simulate ground truth: if EAR < 0.20 for many consecutive frames → closed\n",
    "# In a real evaluation, replace this with manually annotated labels\n",
    "def simulate_gt(ear_vals, strict_threshold=0.20, window=5):\n",
    "    gt = []\n",
    "    for i, e in enumerate(ear_vals):\n",
    "        window_vals = ear_vals[max(0,i-window):i+1]\n",
    "        gt.append(1 if np.mean(window_vals) < strict_threshold else 0)\n",
    "    return gt\n",
    "\n",
    "y_true = simulate_gt(ear_values)\n",
    "\n",
    "thresholds = np.arange(0.15, 0.42, 0.02)\n",
    "precisions, recalls, f1s = [], [], []\n",
    "\n",
    "for thr in thresholds:\n",
    "    y_pred = [1 if e < thr else 0 for e in ear_values]\n",
    "    tp = sum(p==1 and g==1 for p,g in zip(y_pred, y_true))\n",
    "    fp = sum(p==1 and g==0 for p,g in zip(y_pred, y_true))\n",
    "    fn = sum(p==0 and g==1 for p,g in zip(y_pred, y_true))\n",
    "    prec = tp/(tp+fp+1e-9)\n",
    "    rec  = tp/(tp+fn+1e-9)\n",
    "    f1   = 2*prec*rec/(prec+rec+1e-9)\n",
    "    precisions.append(prec); recalls.append(rec); f1s.append(f1)\n",
    "\n",
    "best_idx = np.argmax(f1s)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n",
    "fig.suptitle('Ablation Study: EAR Threshold Sensitivity', fontsize=13, fontweight='bold')\n",
    "\n",
    "axes[0].plot(thresholds, precisions, 'b-o', ms=5, label='Precision')\n",
    "axes[0].plot(thresholds, recalls, 'g-s', ms=5, label='Recall')\n",
    "axes[0].plot(thresholds, f1s, 'r-^', ms=5, label='F1')\n",
    "axes[0].axvline(thresholds[best_idx], color='red', linestyle='--',\n",
    "                label=f'Best F1={f1s[best_idx]:.3f} @ thr={thresholds[best_idx]:.2f}')\n",
    "axes[0].set_xlabel('EAR Threshold'); axes[0].set_ylabel('Score')\n",
    "axes[0].set_title('Precision / Recall / F1 vs Threshold')\n",
    "axes[0].legend(fontsize=8); axes[0].grid(alpha=0.3)\n",
    "\n",
    "axes[1].fill_between(recalls, precisions, alpha=0.3, color='blue')\n",
    "axes[1].plot(recalls, precisions, 'b-o', ms=4)\n",
    "axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')\n",
    "axes[1].set_title('Precision-Recall Curve')\n",
    "axes[1].grid(alpha=0.3); axes[1].set_xlim(0,1); axes[1].set_ylim(0,1)\n",
    "\n",
    "plt.tight_layout()\n",
    "ABLATION_PATH = f'{RESULTS}/ear_ablation.png'\n",
    "plt.savefig(ABLATION_PATH, dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print(f'Best EAR threshold: {thresholds[best_idx]:.2f}')\n",
    "print(f'Best F1 score: {f1s[best_idx]:.3f}')\n",
    "print(f'Saved: {ABLATION_PATH}')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 19 — Confusion matrix\n",
    "# Use your video's alert_level predictions\n",
    "# For real evaluation: manually annotate 50+ clips\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# NOTE: For the actual evaluation, replace y_true_manual below\n",
    "# with your manually annotated ground-truth labels (0/1/2)\n",
    "# You can annotate ~100 frames by watching the video\n",
    "\n",
    "# For now: use the system's own predictions vs a slightly\n",
    "# stricter version (demonstrates the evaluation framework)\n",
    "y_pred = np.array(metrics_log['alert_level'])\n",
    "\n",
    "# Simulate slightly different ground truth for demo\n",
    "# (In reality: replace with hand-annotated labels)\n",
    "np.random.seed(42)\n",
    "noise = np.random.choice([-1,0,0,0,1], size=len(y_pred))\n",
    "y_true_sim = np.clip(y_pred + noise, 0, 2)\n",
    "\n",
    "from sklearn.metrics import confusion_matrix, classification_report\n",
    "\n",
    "cm = confusion_matrix(y_true_sim, y_pred)\n",
    "cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
    "fig.suptitle('System-Level Confusion Matrix', fontsize=13, fontweight='bold')\n",
    "\n",
    "class_names = ['Safe', 'Warning', 'Critical']\n",
    "\n",
    "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',\n",
    "            xticklabels=class_names, yticklabels=class_names, ax=axes[0])\n",
    "axes[0].set_xlabel('Predicted'); axes[0].set_ylabel('True')\n",
    "axes[0].set_title('Raw counts')\n",
    "\n",
    "sns.heatmap(cm_norm, annot=True, fmt='.1%', cmap='Greens',\n",
    "            xticklabels=class_names, yticklabels=class_names, ax=axes[1])\n",
    "axes[1].set_xlabel('Predicted'); axes[1].set_ylabel('True')\n",
    "axes[1].set_title('Normalized')\n",
    "\n",
    "plt.tight_layout()\n",
    "CM_PATH = f'{RESULTS}/confusion_matrix.png'\n",
    "plt.savefig(CM_PATH, dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print(classification_report(y_true_sim, y_pred, target_names=class_names))\n",
    "print(f'Saved: {CM_PATH}')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 9 — Export & Benchmark"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 20 — Export ONNX and TFLite\n",
    "# ══════════════════════════════════════════════════════════\n",
    "from ultralytics import YOLO\n",
    "import os\n",
    "\n",
    "# Use fine-tuned weights if available, else pretrained\n",
    "BEST_PT = f'{MODELS}/phone_yolov8n/weights/best.pt'\n",
    "WEIGHTS = BEST_PT if os.path.exists(BEST_PT) else 'yolov8n.pt'\n",
    "print(f'Using weights: {WEIGHTS}')\n",
    "\n",
    "model = YOLO(WEIGHTS)\n",
    "\n",
    "# Export to ONNX\n",
    "print('Exporting to ONNX...')\n",
    "model.export(format='onnx', opset=17, simplify=True, imgsz=640)\n",
    "print('  ONNX export done.')\n",
    "\n",
    "# Export to TFLite\n",
    "print('Exporting to TFLite...')\n",
    "model.export(format='tflite', imgsz=640)\n",
    "print('  TFLite export done.')\n",
    "\n",
    "# Copy exports to Drive\n",
    "import shutil, glob\n",
    "for ext in ['*.onnx', '*.tflite']:\n",
    "    for f in glob.glob(f'/content/**/{ext}', recursive=True):\n",
    "        dst = f'{MODELS}/{os.path.basename(f)}'\n",
    "        shutil.copy2(f, dst)\n",
    "        print(f'  Saved to Drive: {dst}')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 21 — FPS Benchmark: PyTorch vs ONNX vs Full Pipeline\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import time, numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from ultralytics import YOLO\n",
    "\n",
    "def benchmark_model(model, n=100, img_size=640, label=''):\n",
    "    dummy = np.random.randint(0, 255, (img_size, img_size, 3), dtype=np.uint8)\n",
    "    for _ in range(5):  # warmup\n",
    "        model(dummy, verbose=False)\n",
    "    times = []\n",
    "    for _ in range(n):\n",
    "        t0 = time.perf_counter()\n",
    "        model(dummy, verbose=False)\n",
    "        times.append((time.perf_counter() - t0) * 1000)\n",
    "    times = np.array(times)\n",
    "    print(f'{label:25s}: mean={np.mean(times):.1f}ms  std={np.std(times):.1f}ms  FPS={1000/np.mean(times):.1f}  P95={np.percentile(times,95):.1f}ms')\n",
    "    return times\n",
    "\n",
    "results_bench = {}\n",
    "\n",
    "print('Benchmarking inference speed (100 runs each)...')\n",
    "print('-' * 70)\n",
    "\n",
    "pt_model   = YOLO('yolov8n.pt')\n",
    "t_pt = benchmark_model(pt_model, label='YOLOv8n (PyTorch)')\n",
    "results_bench['PyTorch'] = t_pt\n",
    "\n",
    "import glob, os\n",
    "onnx_files = glob.glob('/content/**/*.onnx', recursive=True)\n",
    "if onnx_files:\n",
    "    onnx_model = YOLO(onnx_files[0])\n",
    "    t_onnx = benchmark_model(onnx_model, label='YOLOv8n (ONNX)')\n",
    "    results_bench['ONNX'] = t_onnx\n",
    "\n",
    "# Full pipeline benchmark (face mesh + all detectors)\n",
    "dummy_frame = np.random.randint(0, 255, (480, 640, 3), dtype=np.uint8)\n",
    "pipe_times = []\n",
    "for _ in range(50):\n",
    "    t0 = time.perf_counter()\n",
    "    process_frame(dummy_frame, use_phone_det=True)\n",
    "    pipe_times.append((time.perf_counter() - t0) * 1000)\n",
    "pipe_times = np.array(pipe_times)\n",
    "print(f'{\"Full pipeline (all modules)\":25s}: mean={np.mean(pipe_times):.1f}ms  std={np.std(pipe_times):.1f}ms  FPS={1000/np.mean(pipe_times):.1f}  P95={np.percentile(pipe_times,95):.1f}ms')\n",
    "results_bench['Full pipeline'] = pipe_times\n",
    "\n",
    "# Plot\n",
    "fig, ax = plt.subplots(figsize=(10, 4))\n",
    "labels  = list(results_bench.keys())\n",
    "means   = [np.mean(v) for v in results_bench.values()]\n",
    "fps_vals= [1000/m for m in means]\n",
    "\n",
    "bars = ax.bar(labels, fps_vals, color=['#2196F3','#4CAF50','#FF9800'][:len(labels)], width=0.5)\n",
    "ax.set_ylabel('FPS'); ax.set_title('Inference Speed Benchmark', fontweight='bold')\n",
    "for bar, fps_v, ms in zip(bars, fps_vals, means):\n",
    "    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,\n",
    "            f'{fps_v:.1f} FPS\\n({ms:.0f}ms)', ha='center', fontsize=10, fontweight='bold')\n",
    "\n",
    "plt.tight_layout()\n",
    "BENCH_PATH = f'{RESULTS}/fps_benchmark.png'\n",
    "plt.savefig(BENCH_PATH, dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Saved: {BENCH_PATH}')"
   ]
  },

  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["---\n", "## STEP 10 — Download All Results"]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 22 — List all saved results\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import os\n",
    "from pathlib import Path\n",
    "\n",
    "print('All saved results:')\n",
    "print('='*60)\n",
    "for root, dirs, files in os.walk(BASE):\n",
    "    level = root.replace(BASE,'').count(os.sep)\n",
    "    indent = ' ' * 2 * level\n",
    "    print(f'{indent}{os.path.basename(root)}/')\n",
    "    subindent = ' ' * 2 * (level + 1)\n",
    "    for f in files:\n",
    "        fpath = Path(root) / f\n",
    "        size = fpath.stat().st_size / 1024\n",
    "        print(f'{subindent}{f}  ({size:.0f} KB)')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 23 — Download annotated video & plots\n",
    "# ══════════════════════════════════════════════════════════\n",
    "from google.colab import files\n",
    "import os\n",
    "\n",
    "downloads = [\n",
    "    (f'{RESULTS}/output_annotated.mp4',   'Annotated output video'),\n",
    "    (f'{RESULTS}/metrics_dashboard.png',  'Metrics dashboard plot'),\n",
    "    (f'{RESULTS}/ear_ablation.png',       'EAR ablation study'),\n",
    "    (f'{RESULTS}/confusion_matrix.png',   'Confusion matrix'),\n",
    "    (f'{RESULTS}/fps_benchmark.png',      'FPS benchmark'),\n",
    "]\n",
    "\n",
    "for path, name in downloads:\n",
    "    if os.path.exists(path):\n",
    "        print(f'Downloading: {name}...')\n",
    "        files.download(path)\n",
    "    else:\n",
    "        print(f'[SKIP] {name} not found (may not have been generated yet)')\n",
    "\n",
    "print('\\nAll results are also saved to your Google Drive at:')\n",
    "print(f'  {BASE}')"
   ]
  },

  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ══════════════════════════════════════════════════════════\n",
    "# CELL 24 — Final summary printout\n",
    "# Copy this into your report's Results section\n",
    "# ══════════════════════════════════════════════════════════\n",
    "import numpy as np\n",
    "\n",
    "alert_arr = np.array(metrics_log['alert_level'])\n",
    "fps_arr   = np.array(metrics_log['fps'])\n",
    "ear_arr   = np.array(metrics_log['ear'])\n",
    "mar_arr   = np.array(metrics_log['mar'])\n",
    "\n",
    "print('='*60)\n",
    "print('DRIVER MONITORING SYSTEM — RESULTS SUMMARY')\n",
    "print('='*60)\n",
    "print(f'Video duration        : {len(alert_arr)/fps_src:.1f} seconds')\n",
    "print(f'Total frames          : {len(alert_arr)}')\n",
    "print()\n",
    "print('--- Detection metrics ---')\n",
    "print(f'EAR   mean/min/max    : {np.mean(ear_arr):.3f} / {np.min(ear_arr):.3f} / {np.max(ear_arr):.3f}')\n",
    "print(f'MAR   mean/max        : {np.mean(mar_arr):.3f} / {np.max(mar_arr):.3f}')\n",
    "print(f'Drowsy frames (EAR<0.25) : {(ear_arr<0.25).sum()} ({100*(ear_arr<0.25).mean():.1f}%)')\n",
    "print(f'Yawn frames (MAR>0.60)   : {(mar_arr>0.60).sum()} ({100*(mar_arr>0.60).mean():.1f}%)')\n",
    "print(f'Phone detected frames    : {sum(metrics_log[\"phone\"])} ({100*np.mean(metrics_log[\"phone\"]):.1f}%)')\n",
    "print()\n",
    "print('--- Alert distribution ---')\n",
    "print(f'Safe     (Level 0): {(alert_arr==0).sum():5d} frames ({100*(alert_arr==0).mean():.1f}%)')\n",
    "print(f'Warning  (Level 1): {(alert_arr==1).sum():5d} frames ({100*(alert_arr==1).mean():.1f}%)')\n",
    "print(f'Critical (Level 2): {(alert_arr==2).sum():5d} frames ({100*(alert_arr==2).mean():.1f}%)')\n",
    "print()\n",
    "print('--- Inference speed ---')\n",
    "print(f'Average FPS           : {np.mean(fps_arr):.1f}')\n",
    "print(f'Min FPS               : {np.min(fps_arr):.1f}')\n",
    "print(f'P95 latency           : {np.percentile(1000/fps_arr, 95):.1f} ms')\n",
    "print('='*60)"
   ]
  }
 ]
}
